# Generated by Django 6.1.1 on 2026-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('MISSING_IN_SYSTEM_B', 'Missing in System B'), ('ORPHAN_IN_SYSTEM_B', 'Orphan in System B'), ('DUPLICATE_IN_SYSTEM_B', 'Duplicate in System B'), ('VALUE_MISMATCH', 'Value Mismatch')], max_length=50)),
                ('record_id', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('org_id', models.CharField(max_length=100)),
                ('val_a', models.TextField(blank=True)),
                ('val_b', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=100, unique=True)),
                ('org_id', models.CharField(max_length=100)),
                ('location_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('event_date', models.CharField(blank=True, max_length=100)),
                ('category_code', models.CharField(blank=True, max_length=100)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('base_value', models.TextField(blank=True)),
                ('adjustment', models.TextField(blank=True)),
                ('total_value', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=100)),
                ('record_ref', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('recorded_on', models.CharField(blank=True, max_length=100)),
                ('value', models.TextField(blank=True)),
                ('label', models.TextField(blank=True)),
            ],
        ),
    ]
